version: '3'
services:
 my-redis:
  container_name: redis
  image: redis/redis-stack
  networks:
    common-network:
      ipv4_address: 172.16.0.1
  ports:
    - '6379:6379'
  command: redis-server --requirepass 123456 --save 20 1 --loglevel warning --protected-mode no  --loadmodule /opt/redis-stack/lib/redisearch.so --loadmodule /opt/redis-stack/lib/rejson.so
 my-mysql:
   container_name: mysql
   image: mysql:5.7
   restart: always
   networks:
     common-network:
       ipv4_address: 172.16.0.2
   environment:
     MYSQL_ROOT_PASSWORD: admin
   volumes:
     - /data/mysql/conf.d:/etc/mysql/conf.d
     - /data/mysql/data/:/var/lib/mysql
   ports:
     - '3306:3306'
 search-trek:
  container_name: SearchTrek
  build: ./search-trek
  restart: always
  networks:
    common-network:
      ipv4_address: 172.16.0.3
  ports:
    - '8080:8080'
